version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - package-lock.json
    - src/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no